title: Yana Agun Siswanto's blog
email: yana.developer@gmail.com 
description: > 
  Documenting experience. My experience.
baseurl: ""
url: "bekicot.github.com"
twitter_username: yana_agun
github_username: bekicot
markdown: kramdown
collections:
  posts:
    output: true
    permalink: /blog/:title
exclude:
  - tmp
  - tags
  - tags.lock
plugins:
  - jekyll-sitemap
